spin_manifest_version = 2

[application]
name = "customer-service"
version = "0.1.0"

[variables]
db_url = { required = true }

[[trigger.http]]
route = "/..."
component = "customer-service"

[component.customer-service]
source = "target/wasm32-wasip1/release/customer_service.wasm"
allowed_outbound_hosts = ["postgres://postgres.db.svc.cluster.local:5432"]

[component.customer-service.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.customer-service.variables]
db_url = "{{ db_url }}"
